export class PatientsInfo {
    public Id: number                           ;
    public FormDate: any;
    public MS_Comp_Id: number;
    public Patients_Appointment_Id: number;
    public FName: string;
    public LName: string;
    public FullName: string;
    public DOB: any;
    public Mobile1: number;
    public Mobile2: number;
    public AddressLine1: string;
    public AddressLine2: string;
    public MS_City_Id: number;
    public CityName: string;
    public MS_State_Id: number;
    public StateName: string;
    public PostalCode: number;
    public MaritialStatus: string;
    public MS_Reference_Id: number;
    public Reference: string;
    public MS_Treament_Id: number;
    public TreamentName: string;
    public MS_User_Id: number;
    public UserFullName: string;
    public IsSummaryGenerated: string;
    public OtherReferenceName: string;
    public Remark: string;
    public VisitDate: any;
}